language: csharp
solution: BrainFucker.sln

install:
  - nuget restore BrainFucker.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BrainFucker.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./BrainFuckerTests/bin/Release/BrainFuckerTests.dll
